replicaCount: 1
image:
  repository: dpage/pgadmin4
  tag:
  pullPolicy: IfNotPresent
service:
  name: pgadmin
  type: NodePort
  externalPort: 80
  internalPort: 80
ingress:
  enabled: false
  staticIPReservation: pgadmin-static-ip
  tls:
    enabled: false
    clusterIssuer: letsencrypt-staging
    externalDNSName: pgadmin.example.com
pgadmin:
  username: admin
  password: passw0rd
persistence:
  enabled: true
  #storageClass:
  accessMode: ReadWriteOnce
  size: 4Gi
resources: {}

